### PR TITLE
Revert "Enhancements"

### PR DESCRIPTION
**Pull request by aureamunoz**
Merged by mistake, could you please take a look to the license please @geoand ?

### CODE REVIEW

**Comment by geoand** [comment]
I don't really know much about licenses. Perhaps @gytis can elighten us?

**Comment by gytis** [comment]
@geoand what is the actual issue? Normally we add Apache v2 as a file and pom.xml entry.

**Comment by gytis** [comment]
Like https://github.com/snowdrop/vertx-spring-boot/blob/master/LICENSE and https://github.com/snowdrop/vertx-spring-boot/blob/master/pom.xml#L13

**Comment by geoand** [comment]
That's what I thought as well, but I wanted your opinion since you know a ton more. @aureamunoz do you need any more information?

**Comment by gytis** [comment]
Also, many projects also add headers to each file (*.xml and *.java mainly) as well with apache license. But I don't remember if that is a requirement or just a nice to have.

**Pull request closed without merging**
